# Generated by Django 3.1.1 on 2020-09-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, verbose_name='카테고리')),
                ('subject', models.CharField(max_length=256, verbose_name='제목')),
                ('reg_date_time', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'bk_board',
            },
        ),
    ]
