# Generated by Django 3.1.1 on 2020-09-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='reg_date_time',
            new_name='registered_dttm',
        ),
    ]
