# Generated by Django 3.1.1 on 2020-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200915_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
