# Generated by Django 3.1.1 on 2020-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200915_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=64, verbose_name='사용자명'),
        ),
    ]
