# Generated by Django 3.1.1 on 2020-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200917_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='비밀번호'),
        ),
    ]
