# Generated by Django 3.1.1 on 2020-09-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200917_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkuser',
            name='save_info',
            field=models.CharField(default='temp@temp.com', max_length=8, verbose_name='아이디 저장'),
            preserve_default=False,
        ),
    ]
